BEGIN;

DROP TABLE IF EXISTS part_vehicle_compatibility;
DROP TABLE IF EXISTS telemetry_data;
DROP TABLE IF EXISTS service_records;
DROP TABLE IF EXISTS parts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS vehicles;

CREATE TABLE vehicles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin VARCHAR NOT NULL,
    make VARCHAR NOT NULL,
    model VARCHAR NOT NULL,
    year INTEGER NOT NULL,
    engine_type VARCHAR,
    status VARCHAR(14)
);

CREATE TABLE parts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    quantity INTEGER,
    supplier VARCHAR,
    compatible_makes VARCHAR
);

CREATE TABLE telemetry_data (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id INTEGER NOT NULL,
    timestamp TIMESTAMP,
    speed DOUBLE PRECISION,
    engine_rpm DOUBLE PRECISION,
    coolant_temp DOUBLE PRECISION,
    CONSTRAINT fk_telemetry_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
);

CREATE TABLE service_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id INTEGER NOT NULL,
    date TIMESTAMP,
    description VARCHAR NOT NULL,
    cost DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_service_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR NOT NULL,
    hashed_password VARCHAR NOT NULL
);

CREATE TABLE part_vehicle_compatibility (
    part_id INTEGER NOT NULL,
    vehicle_id INTEGER NOT NULL,
    PRIMARY KEY (part_id, vehicle_id),
    CONSTRAINT fk_pvc_part FOREIGN KEY (part_id) REFERENCES parts (id),
    CONSTRAINT fk_pvc_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
);

INSERT INTO vehicles (id, vin, make, model, year, engine_type, status) VALUES
    (1, 'string', 'string', 'string', 0, 'string', 'ACTIVE'),
    (2, 'stringstringstrin', 'string', 'string', 0, 'string', 'ACTIVE');

SELECT setval(pg_get_serial_sequence('vehicles', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM vehicles;
SELECT setval(pg_get_serial_sequence('parts', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM parts;
SELECT setval(pg_get_serial_sequence('telemetry_data', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM telemetry_data;
SELECT setval(pg_get_serial_sequence('service_records', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM service_records;
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM users;

CREATE INDEX ix_vehicles_make ON vehicles (make);
CREATE INDEX ix_vehicles_id ON vehicles (id);
CREATE UNIQUE INDEX ix_vehicles_vin ON vehicles (vin);
CREATE INDEX ix_vehicles_model ON vehicles (model);
CREATE UNIQUE INDEX ix_parts_part_number ON parts (part_number);
CREATE INDEX ix_parts_id ON parts (id);
CREATE INDEX ix_telemetry_data_timestamp ON telemetry_data (timestamp);
CREATE INDEX ix_telemetry_data_id ON telemetry_data (id);
CREATE INDEX ix_service_records_id ON service_records (id);
CREATE UNIQUE INDEX ix_users_username ON users (username);
CREATE INDEX ix_users_id ON users (id);

COMMIT;
